const books = [
  { badge: 'First in the Series', title: 'The Power of Influencers on Social Media', subtitle: 'In the Digital Revolution', edition: 'Arabic & English · 2023', text: 'Why a phone and a following now rival newspapers and broadcasters, and what that shift means for audiences, brands and regulators.', style: 'bg-ink text-white', icon: '/assets/bk-icon1.svg' },
  { badge: 'Braille Edition', title: '50 Metaversal Shots', subtitle: 'Fifty Glimpses of the Metaverse', edition: '2024 · Braille edition with Al-Akhbar Braille Foundation', text: 'Fifty short readings on life, identity and influence in virtual worlds, also published in Braille so readers with visual impairments can access it.', style: 'bg-amber-600 text-white', icon: '/assets/bk-icon2.svg' },
  { badge: 'Signature Title', title: 'Influencers Planet', subtitle: 'The Rules of a New Media World', edition: 'Arabic & English · 2025', text: 'The book that named the platform: a guide to the influencer economy, digital credibility and the ethics every creator should follow.', style: 'bg-amber-400 text-ink', icon: '/assets/bk-icon3.svg' },
];
const initiatives = [
  { icon: '/assets/pr-icon1.svg', title: 'The Influencer Code of Conduct', text: 'The first ethical and professional code for influencers in the region segmented by age, covering transparency, paid-content disclosure and audience protection.', action: 'Read the Code' },
  { icon: '/assets/pr-icon2.svg', title: 'Child Influencer Protection Framework', text: 'A dedicated framework for children on camera, addressing privacy, exploitation, financial rights and digital working conditions.', action: 'Request the Framework' },
  { icon: '/assets/pr-icon3.svg', title: 'Influencers Planet Blogs & Vlogs', text: 'More than 120 short pieces on influence, AI and cybersecurity, published weekly on social media since 2025.', action: 'Watch the Latest' },
];
export default function Products() {
  return <section id="products" className="bg-stone-50 py-12"><div className="container-page flex flex-col gap-12">
    <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="flex max-w-[672px] flex-col items-start gap-1"><span className="eyebrow pill bg-amber-500/20">Published Works</span><h2 className="h2">Seven Books on the Power and Responsibility of Influence</h2><p className="lede">Written over four consecutive years and showcased at the Cairo International Book Fair in Arabic and English, the series traces how influence is built, monetised, abused and protected.</p></div><a href="#contact" className="btn-label text-link">View All Publications <img src="/assets/bk-arrow.svg" alt="" /></a></div>
    <div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{books.map((book) => <article key={book.title} className="flex flex-col rounded-3xl border-2 border-ink bg-white p-[18px] shadow-ink-4"><div className={`flex min-h-[350px] flex-col justify-between rounded-2xl border-2 border-ink p-[30px] text-center ${book.style}`}><span className="self-start rounded-full bg-white/90 px-3 py-1 text-xs font-extrabold uppercase text-ink">{book.badge}</span><div className="flex flex-col items-center gap-2"><img src={book.icon} alt="" /><h3 className="font-display text-2xl font-extrabold">{book.title}</h3><p className="text-sm italic">{book.subtitle}</p></div><p className="text-xs font-extrabold uppercase tracking-widest">Dr. Germien Amer</p></div><div className="flex flex-1 flex-col gap-1 pt-4"><p className="eyebrow text-amber-600">{book.edition}</p><p className="text-sm leading-[22.75px]">{book.text}</p><div className="mt-auto flex flex-wrap gap-2 pt-4"><a href="#contact" className="rounded-xl border border-amber-500/40 bg-amber-50 px-3 py-2 text-xs font-bold text-ink">Request a Copy</a><a href="#contact" className="rounded-xl border border-ink/20 px-3 py-2 text-xs font-bold text-ink">{book.badge === 'Braille Edition' ? 'About the Braille Edition' : 'Read an Excerpt'}</a></div></div></article>)}</div>
    <p className="text-sm text-zinc-600"><strong className="text-ink">Also by Dr. Amer:</strong> Tale of Influencers Planets (2026) · Cyber-crime&apos;s Theatre (2026) · Two further titles to be announced</p>
    <div className="flex flex-col gap-4 rounded-3xl border-2 border-amber-500/50 bg-gradient-to-r from-amber-50 via-white to-amber-50 p-[30px]"><div className="flex flex-col items-start"><span className="eyebrow pill bg-amber-500">Beyond the Books</span><h3 className="h3 pt-2">Frameworks for a Responsible Influence Economy</h3><p className="text-sm leading-[23.2px]">Practical tools built from the research, for creators, parents, brands and institutions.</p></div><div className="grid gap-4 md:grid-cols-3">{initiatives.map((item) => <article key={item.title} className="flex flex-col gap-4 rounded-2xl border-2 border-ink/20 bg-white p-[18px]"><img src={item.icon} alt="" /><h4 className="font-display text-lg font-bold text-ink">{item.title}</h4><p className="text-sm leading-[23.2px]">{item.text}</p><a href="#contact" className="eyebrow press mt-auto self-start rounded-full border border-ink bg-amber-500 px-4 py-2">{item.action}</a></article>)}</div></div>
  </div></section>;
}
